version: '2'
services:
    app:
            image: app:1.0
            #restart: always
            build: .
            command: >
                sh -c "python manage.py makemigrations &&
                       python manage.py migrate &&
                       python manage.py runserver 0.0.0.0:5555"
            container_name: app
#            env_file:
#              - ./.env
#            volumes:
#                    - .:/app
            network_mode: host
            ports:
                - "0.0.0.0:5555:5555"

#            environment:
#                kavan_main_db_ip: 159.69.68.242
#                kavan_main_db_port: 3306
#                kavan_main_db_name: kavan_main_0.1.0
#                kavan_main_db_pass: MReUn6bxZnuVp72VutrZKyYFi4XuGhMSu
#                kavan_main_user: root
#                kavan_publisher_db_ip: 138.201.84.41
#                kavan_publisher_db_port: 3306
#                kavan_publisher_db_name: kavan_publisher_1_0_0
#                kavan_publishern_db_pass: V4bxd%XGd/3Cr3MTb.KH
#                kavan_publisher_user: root
#
